# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

language: java

jdk:
  - openjdk8

#don't build tags
branches:
  except:
  - /^v\d/

#Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
install:
 - true

script:
  - ./gradlew build --scan && ./gradlew bintrayUpload --scan -PdryRun # && ./gradlew createTag pushTag bintrayUpload --scan